# Generated by Django 3.2.7 on 2025-09-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('tel', models.CharField(max_length=20, verbose_name='电话')),
                ('email', models.EmailField(max_length=40)),
                ('content', models.TextField(verbose_name='留言内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('ipaddress', models.CharField(max_length=20, verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言列表',
            },
        ),
    ]
