# Generated by Django 3.2.7 on 2025-09-09 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布日期'),
        ),
    ]
