# Generated by Django 3.2.7 on 2025-09-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_set', '0002_alter_site_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.TextField(blank=True, unique=True, verbose_name='地址'),
        ),
    ]
