# Generated by Django 3.2.7 on 2025-09-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, unique=True, verbose_name='请在此添加1个产品标签')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品标签',
                'verbose_name_plural': '产品标签',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(max_length=50, verbose_name='排序')),
                ('name', models.CharField(max_length=100, verbose_name='岗位名称')),
                ('age', models.CharField(max_length=100, verbose_name='年龄要求')),
                ('xueli', models.CharField(max_length=100, verbose_name='学历要求')),
                ('address', models.CharField(max_length=150, verbose_name='工作地点')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='职位描述')),
                ('yaoqiu', models.TextField(blank=True, null=True, verbose_name='任职要求')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '招聘岗位',
                'verbose_name_plural': '人才招聘',
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, unique=True, verbose_name='请在此添加1个文章标签')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='单页名称')),
                ('url', models.CharField(help_text='请谨慎，URL一旦保存不能修改', max_length=20, unique=True, verbose_name='url后缀名')),
                ('is_bar', models.BooleanField(default=True, verbose_name='是否加入导航')),
                ('sort', models.SmallIntegerField(blank=True, null=True, verbose_name='指定排序')),
                ('is_sitemap', models.BooleanField(default=False, verbose_name='是否加入站点地图')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='seo标题')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='seo关键词')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='seo描述')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '单页',
                'verbose_name_plural': '单页管理',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TuWenTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, unique=True, verbose_name='请在此添加1个图文标签')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '图文标签',
                'verbose_name_plural': '图文标签',
            },
        ),
    ]
