# Generated by Django 3.2.7 on 2025-09-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='sort',
            field=models.IntegerField(verbose_name='排序'),
        ),
    ]
