# Generated by Django 3.2.7 on 2025-09-09 15:23

from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuWen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='图文名称')),
                ('url', models.CharField(help_text='请谨慎，URL一旦保存不能修改', max_length=50, unique=True, verbose_name='url后缀名')),
                ('c_url', models.CharField(max_length=50, verbose_name='上级url')),
                ('is_topping', models.BooleanField(default=True, verbose_name='是否置顶')),
                ('sort', models.SmallIntegerField(null=True, verbose_name='指定排序')),
                ('file_upload', models.FileField(blank=True, default='', upload_to='files', verbose_name='文件上传')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='seo标题')),
                ('keywords', models.CharField(max_length=255, unique=True, verbose_name='seo关键词')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='seo描述')),
                ('splj', models.CharField(max_length=150, verbose_name='视频地址')),
                ('is_sitemap', models.BooleanField(default=False, verbose_name='是否加入站点地图')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='内容摘要(选填)')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods_tag', models.ManyToManyField(blank=True, to='page.GoodsTag', verbose_name='相关产品')),
            ],
            options={
                'verbose_name': '图文信息',
                'verbose_name_plural': '图文信息',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TuWenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', smartfields.fields.ImageField(upload_to='goods_images', verbose_name='请上传图片')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片标签')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tuwen.tuwen', verbose_name='项目图片')),
            ],
            options={
                'verbose_name_plural': '上传项目预览图片',
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TuWenCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='图文分类名称')),
                ('url', models.CharField(help_text='请谨慎，URL一旦保存不能修改', max_length=50, unique=True, verbose_name='url后缀名')),
                ('sort', models.SmallIntegerField(null=True, verbose_name='指定排序')),
                ('image', smartfields.fields.ImageField(blank=True, upload_to='tuwen_c_images', verbose_name='默认图片')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='seo标题')),
                ('keywords', models.CharField(max_length=255, unique=True, verbose_name='seo关键词')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='seo描述')),
                ('jianjie', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('is_sitemap', models.BooleanField(default=True, verbose_name='是否加入站点地图')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuwen_c', to='tuwen.tuwencatalog', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '图文分类',
                'verbose_name_plural': '图文分类',
                'ordering': ['id'],
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='tuwen',
            name='tuwen_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuwen.tuwencatalog', verbose_name='图文类别'),
        ),
        migrations.AddField(
            model_name='tuwen',
            name='tuwen_tag',
            field=models.ManyToManyField(blank=True, to='page.TuWenTag', verbose_name='相关图文'),
        ),
    ]
