# Generated by Django 3.2.7 on 2025-09-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='移动站幻灯标题')),
                ('linkurl', models.CharField(max_length=255, unique=True, verbose_name='链接地址')),
                ('m_image', models.ImageField(default=None, upload_to='news_images', verbose_name='幻灯图片')),
                ('sort', models.SmallIntegerField(null=True, verbose_name='指定排序')),
            ],
            options={
                'verbose_name': '移动站幻灯',
                'verbose_name_plural': '移动站幻灯',
            },
        ),
        migrations.CreateModel(
            name='PCSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='PC幻灯标题')),
                ('linkurl', models.CharField(max_length=255, unique=True, verbose_name='链接地址')),
                ('pc_image', models.ImageField(default=None, upload_to='news_images', verbose_name='幻灯图片')),
                ('sort', models.SmallIntegerField(null=True, verbose_name='指定排序')),
            ],
            options={
                'verbose_name': 'PC站幻灯',
                'verbose_name_plural': 'PC站幻灯',
            },
        ),
    ]
