# Generated by Django 3.2.7 on 2025-09-09 15:23

from django.db import migrations, models
import django.db.models.deletion
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='产品名称')),
                ('url', models.CharField(help_text='请谨慎，URL一旦保存不能修改', max_length=100, unique=True, verbose_name='url后缀名')),
                ('c_url', models.CharField(default='', max_length=100, verbose_name='上级url')),
                ('is_topping', models.BooleanField(default=True, verbose_name='是否置顶')),
                ('sort', models.SmallIntegerField(null=True, verbose_name='指定排序')),
                ('image', smartfields.fields.ImageField(blank=True, upload_to='goods_images', verbose_name='默认图片')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='seo标题')),
                ('keywords', models.CharField(max_length=255, unique=True, verbose_name='seo关键词')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='seo描述')),
                ('is_sitemap', models.BooleanField(default=True, verbose_name='是否加入站点地图')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='内容摘要(选填)')),
                ('content', models.TextField(blank=True, null=True, verbose_name='产品介绍')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
                'ordering': ['id'],
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', smartfields.fields.ImageField(upload_to='goods_images', verbose_name='请上传图片')),
                ('alt', models.CharField(max_length=255, null=True, verbose_name='图片标签')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='产品图片')),
            ],
            options={
                'verbose_name_plural': '上传产品预览图片',
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GoodsCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='产品分类名称')),
                ('url', models.CharField(help_text='请谨慎，URL一旦保存不能修改', max_length=100, unique=True, verbose_name='url后缀名')),
                ('sort', models.SmallIntegerField(null=True, verbose_name='指定排序')),
                ('image', smartfields.fields.ImageField(blank=True, upload_to='goods_c_images', verbose_name='默认图片')),
                ('title', models.CharField(default='', max_length=255, unique=True, verbose_name='seo标题')),
                ('keywords', models.CharField(default='', max_length=255, unique=True, verbose_name='seo关键词')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='seo描述')),
                ('jianjie', models.TextField(blank=True, null=True, verbose_name='分类简介')),
                ('is_sitemap', models.BooleanField(default=True, verbose_name='是否加入站点地图')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_c', to='goods.goodscatalog', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'ordering': ['id'],
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodscatalog', verbose_name='产品类别'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_tag',
            field=models.ManyToManyField(blank=True, to='page.GoodsTag', verbose_name='相关产品'),
        ),
        migrations.AddField(
            model_name='goods',
            name='news_tag',
            field=models.ManyToManyField(blank=True, to='page.NewsTag', verbose_name='相关文章'),
        ),
        migrations.AddField(
            model_name='goods',
            name='tuwen_tag',
            field=models.ManyToManyField(blank=True, to='page.TuWenTag', verbose_name='相关图文'),
        ),
    ]
