# Generated by Django 3.2.7 on 2025-09-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='示例：尚贤科技的站点地图', max_length=30)),
                ('newscatalog', models.BooleanField(default=True, help_text='文章分类已默认添加至sitemap，并继承已有自定义设置，如需修改请前往管理页面', verbose_name='文章分类')),
                ('goodscatalog', models.BooleanField(default=True, help_text='产品分类已默认添加至sitemap，并继承已有自定义设置，如需修改请前往管理页面', verbose_name='产品分类')),
                ('tuwencatalog', models.BooleanField(default=True, help_text='图文分类已默认添加至sitemap，并继承已有自定义设置，如需修改请前往管理页面', verbose_name='图文分类')),
                ('page', models.BooleanField(default=False, help_text='单页默认不添加sitemap，已继承已有自定义设置，如需修改请前往管理页面', verbose_name='单页面')),
                ('index_w', models.SmallIntegerField(choices=[(1, '0.1'), (2, '0.2'), (3, '0.3'), (4, '0.4'), (5, '0.5'), (6, '0.6'), (7, '0.7'), (8, '0.8'), (9, '0.9'), (10, '1.0')], verbose_name='首页权重')),
                ('catalog_w', models.SmallIntegerField(choices=[(1, '0.1'), (2, '0.2'), (3, '0.3'), (4, '0.4'), (5, '0.5'), (6, '0.6'), (7, '0.7'), (8, '0.8'), (9, '0.9'), (10, '1.0')], verbose_name='分类页权重')),
                ('inner_w', models.SmallIntegerField(choices=[(1, '0.1'), (2, '0.2'), (3, '0.3'), (4, '0.4'), (5, '0.5'), (6, '0.6'), (7, '0.7'), (8, '0.8'), (9, '0.9'), (10, '1.0')], verbose_name='落地页权重')),
                ('page_w', models.SmallIntegerField(choices=[(1, '0.1'), (2, '0.2'), (3, '0.3'), (4, '0.4'), (5, '0.5'), (6, '0.6'), (7, '0.7'), (8, '0.8'), (9, '0.9'), (10, '1.0')], verbose_name='单页权重')),
                ('index_f', models.SmallIntegerField(choices=[(1, 'always'), (2, 'hourly'), (3, 'weekly'), (4, 'monthly'), (5, 'yearly'), (6, 'never')], verbose_name='首页更新频率')),
                ('catalog_f', models.SmallIntegerField(choices=[(1, 'always'), (2, 'hourly'), (3, 'weekly'), (4, 'monthly'), (5, 'yearly'), (6, 'never')], verbose_name='分类页更新频率')),
                ('inner_f', models.SmallIntegerField(choices=[(1, 'always'), (2, 'hourly'), (3, 'weekly'), (4, 'monthly'), (5, 'yearly'), (6, 'never')], verbose_name='落地页更新频率')),
                ('page_f', models.SmallIntegerField(choices=[(1, 'always'), (2, 'hourly'), (3, 'weekly'), (4, 'monthly'), (5, 'yearly'), (6, 'never')], verbose_name='单页更新频率')),
            ],
            options={
                'verbose_name_plural': '站点地图',
            },
        ),
    ]
