# Generated by Django 3.2.7 on 2025-09-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('goods', '0001_initial'),
        ('tuwen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, unique=True, verbose_name='链接词')),
                ('links_url', models.CharField(default='', max_length=200, unique=True, verbose_name='URL')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='页面标题')),
                ('url', models.CharField(default='', max_length=50, verbose_name='页面URL')),
                ('number', models.CharField(max_length=30, verbose_name='输出投票数量『个数』')),
                ('content', models.TextField(blank=True, null=True, verbose_name='输出投票清单')),
                ('vote_number', models.SmallIntegerField(default=0, null=True, verbose_name='被投票数量『页数』')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='产品内链列表')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='文章内链列表')),
                ('tuwen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tuwen.tuwen', verbose_name='图文内链列表')),
            ],
            options={
                'verbose_name': '内链统计',
                'verbose_name_plural': '内链统计',
            },
        ),
        migrations.CreateModel(
            name='LinkInner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='投票页面标题')),
                ('vote_url', models.CharField(default='', max_length=50, verbose_name='投票页面url')),
                ('vote_keyword', models.CharField(default='', max_length=100, verbose_name='投票链接词')),
                ('mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.mode', verbose_name='内链详情')),
            ],
        ),
    ]
